tests/linux: rewrite the framework with .test files
Replace the old .source + .options + .exclude + .env optional files with
a single mandatory .test file that contains everything.

foo.test should contain:
- source: tarball filename (must be in same directory as foo.test)
- target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
- options: lstopo options, if any
- exclude: exclude file to be passed to tar --exclude-from=, if any
- env: environment variable lines to be sourced, if any

Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>

diff --git a/tests/hwloc/linux/test-topology.sh.in b/tests/hwloc/linux/test-topology.sh.in
--- a/tests/hwloc/linux/test-topology.sh.in
+++ b/tests/hwloc/linux/test-topology.sh.in
@@ -28,8 +28,6 @@ export HWLOC_XML_EXPORT_SUPPORT
 HWLOC_DEBUG_SORT_CHILDREN=1
 export HWLOC_DEBUG_SORT_CHILDREN
 
-actual_output="$1"
-
 # make sure we use default numeric formats (only XML outputs are dis-localized when supported)
 LANG=C
 LC_ALL=C
@@ -40,36 +38,82 @@ error()
     echo $@ 2>&1
 }
 
+if [ ! -x "$lstopo" ]
+then
+    error "Could not find executable file \`$lstopo'."
+    exit 1
+fi
+
+testname="$1"
+dirname=`dirname $1`
+basename=`basename $1 .test`
+
+if test \! -f "$testname"; then
+  echo "Cannot find test file $testname"
+  exit 1
+fi
+
+dir="`mktemp -d`"
+
+####################################
+# foo.test should contain:
+# - source: tarball filename (must be in same directory as foo.test)
+# - target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
+# - options: lstopo options, if any
+# - exclude: exclude file to be passed to tar --exclude-from=, if any
+# - env: environment variable lines to be sourced, if any
+
+source=`sed -n 's/^source: *//p' "$testname"`
+target=`sed -n 's/^target: *//p' "$testname"`
+opts=`sed -n 's/^options: *//p' "$testname"`
+exclude=`sed -n 's/^exclude: *//p' "$testname"`
+sed -n 's/^env: *//p' "$testname" > "$dir/env"
+
+if test \! -f "$dirname/$source"; then
+  echo "Cannot find source file $source from test $testname"
+  exit 1
+fi
+if test \! -f "$dirname/$target"; then
+  echo "Cannot find target file $target from test $testname"
+  exit 1
+fi
+
+# use an absolute path for tar options because tar is invoked from the temp directory
+[ -f "$dirname/$exclude" ] && tar_options="--exclude-from=$dirname/$exclude"
+
+[ -z "$opts" ] && opts="-v -"
+if test "$target" = `basename $target .xml`".xml"; then
+  is_xml_target=1
+  opts="--of xml $opts"
+else
+  is_xml_target=0
+  opts="--of console $opts"
+fi
+
+. "$dir/env"
+
 # test_topology NAME TOPOLOGY-DIR
 #
 # Test the topology under TOPOLOGY-DIR.  Return true on success.
 test_topology ()
 {
-    local name="$1"
-    local dir="$2"
-    local expected_output="$3"
-    local options="$4"
+    local sysfsdir="$1"
+    local expected_output="$dirname/$target"
 
     local output="`mktemp`"
 
     export HWLOC_DEBUG_CHECK=1
 
-    opts="-v -"
-    [ -r "$options" ] && opts=`cat $options`
-
     # Use HWLOC_COMPONENTS explicitly instead of passing --if fsroot because
     # we don't want the pci backend to annotate PCI vendor/device when supported.
     # We'll set HWLOC_FSROOT and HWLOC_DUMPED_HWDATA_DIR manually below.
-    HWLOC_COMPONENTS=linux,stop
-    export HWLOC_COMPONENTS
-    HWLOC_FSROOT="$dir"
-    export HWLOC_FSROOT
-    HWLOC_DUMPED_HWDATA_DIR=/var/run/hwloc
-    export HWLOC_DUMPED_HWDATA_DIR
+    export HWLOC_COMPONENTS=linux,stop
+    export HWLOC_FSROOT="$sysfsdir"
+    export HWLOC_DUMPED_HWDATA_DIR=/var/run/hwloc
 
     if ! "$lstopo" $opts \
-	| sed	-e 's/ id="obj[0-9]\+"//' \
-	| sed	-e 's/ gp_index="[0-9]\+"//' \
+        | sed   -e 's/ id="obj[0-9]*"//' \
+        | sed   -e 's/ gp_index="[0-9]*"//' \
 	> "$output"
 	# filtered id/gp_index because it depends on the insertiong order, which may depend on pciaccess version, etc
     then
@@ -94,64 +138,17 @@ test_topology ()
     return $result
 }
 
-# test_eligible TOPOLOGY-DIR
-#
-# Return true if the topology under TOPOLOGY-DIR is eligible for
-# testing with the current flavor.
-test_eligible()
-{
-    local dir="$1"
-    local output="$2"
-
-    [ -d "$dir" -a -f "$output" ]
-}
-
-
-if [ ! -x "$lstopo" ]
-then
-    error "Could not find executable file \`$lstopo'."
-    exit 1
-fi
-
-topology="${actual_output%.output}"
-if [ "$topology" = "$actual_output" ] ;
-then
-    error "Input file \`$1' should end with .output"
-    exit 1
-fi
-actual_options="$topology".options
-
-# if there's a .source file, use the tarball name it contains instead of $topology
-if [ -f "$topology".source ] ; then
-    actual_source=`dirname $topology`/`cat "$topology".source`
-else
-    actual_source="$topology".tar.bz2
-fi
-
-# if there's a .env file, source it
-if [ -f "$topology".env ] ; then
-    . "$topology".env
-fi
-
-# use an absolute path for tar options because tar is invoked from the temp directory
-actual_exclude=`dirname $topology`/`basename $topology`.exclude
-[ -f "$actual_exclude" ] && tar_options="--exclude-from=$actual_exclude"
-
 result=1
 
-dir="`mktemp -d`"
-
-if ! ( bunzip2 -c "$actual_source" | ( cd "$dir" && tar xf - $tar_options ) )
+if ! ( bunzip2 -c "$dirname/$source" | ( cd "$dir" && tar xf - $tar_options ) )
 then
-    error "failed to extract topology \`$topology'"
+    error "failed to extract topology \`$source'"
 else
-    actual_dir="`echo "$dir"/*`"
+    actual_dir="`echo "$dir"/*/`"
 
-    if test_eligible "$actual_dir" "$actual_output"
+    if [ -d "$actual_dir" ]
     then
-	test_count="`expr $test_count + 1`"
-
-	test_topology "`basename $topology`" "$actual_dir" "$actual_output" "$actual_options"
+	test_topology "$actual_dir"
 	result=$?
     else
 	# Skip this test.
