tests/x86: rewrite the framework with .test files
Replace the old .options + .env optional files with
a single mandatory .test file that contains everything.

foo.test should contain:
- source: tarball filename (must be in same directory as foo.test)
- target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
- options: lstopo options, if any
- env: environment variable lines to be sourced, if any

Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>

diff --git a/tests/hwloc/x86/test-topology.sh.in b/tests/hwloc/x86/test-topology.sh.in
--- a/tests/hwloc/x86/test-topology.sh.in
+++ b/tests/hwloc/x86/test-topology.sh.in
@@ -2,7 +2,7 @@
 #-*-sh-*-
 
 #
-# Copyright © 2015-2022 Inria.  All rights reserved.
+# Copyright © 2015-2023 Inria.  All rights reserved.
 # See COPYING in top-level directory.
 #
 
@@ -22,9 +22,7 @@ export HWLOC_XML_EXPORT_SUPPORT
 HWLOC_X86_TOPOEXT_NUMANODES=1
 export HWLOC_X86_TOPOEXT_NUMANODES
 
-actual_output="$1"
-
-# make sure we use default numeric formats
+# make sure we use default numeric formats (only XML outputs are dis-localized when supported)
 LANG=C
 LC_ALL=C
 export LANG LC_ALL
@@ -34,36 +32,79 @@ error()
     echo $@ 2>&1
 }
 
+if [ ! -x "$lstopo" ]
+then
+    error "Could not find executable file \`$lstopo'."
+    exit 1
+fi
+
+testname="$1"
+dirname=`dirname $1`
+basename=`basename $1 .test`
+
+if test \! -f "$testname"; then
+  echo "Cannot find test file $testname"
+  exit 1
+fi
+
+dir="`mktemp -d`"
+
+####################################
+# foo.test should contain:
+# - source: tarball filename (must be in same directory as foo.test)
+# - target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
+# - options: lstopo options, if any
+# - env: environment variable lines to be sourced, if any
+
+source=`sed -n 's/^source: *//p' "$testname"`
+target=`sed -n 's/^target: *//p' "$testname"`
+opts=`sed -n 's/^options: *//p' "$testname"`
+sed -n 's/^env: *//p' "$testname" > "$dir/env"
+
+if test \! -f "$dirname/$source"; then
+  echo "Cannot find source file $source from test $testname"
+  exit 1
+fi
+if test \! -f "$dirname/$target"; then
+  echo "Cannot find target file $target from test $testname"
+  exit 1
+fi
+
+[ -z "$opts" ] && opts="--of xml -"
+if test "$target" = `basename $target .xml`".xml"; then
+  is_xml_target=1
+  opts="--of xml $opts"
+else
+  is_xml_target=0
+  opts="--of console $opts"
+fi
+
+. "$dir/env"
+
 # test_topology NAME TOPOLOGY-DIR
 #
 # Test the topology under TOPOLOGY-DIR.  Return true on success.
 test_topology ()
 {
-    local name="$1"
-    local dir="$2"
-    local expected_output="$3"
-    local options="$4"
+    local cpuiddir="$1"
+    local expected_output="$dirname/$target"
 
     local output="`mktemp`"
 
     export HWLOC_THISSYSTEM=0
     export HWLOC_DEBUG_CHECK=1
 
-    opts="--of xml -"
-    [ -r "$options" ] && opts=`cat $options`
-
-    if ! "$lstopo" -i "$dir" --if cpuid $opts \
-	| sed	-e 's/ id="obj[0-9]*"//' \
-	| sed	-e 's/ gp_index="[0-9]*"//' \
+    if ! "$lstopo" -i "$cpuiddir" --if cpuid $opts \
+        | sed   -e 's/ id="obj[0-9]*"//' \
+        | sed   -e 's/ gp_index="[0-9]*"//' \
 	> "$output"
-	# filtered id/gp_index because it may change if we reorder discovery
-	# (not used in NUMA/PU distances, and regenerated (differently) during XML import).
+	# filtered id/gp_index because it depends on the insertiong order, etc
     then
 	result=1
     else
 	if [ "$HWLOC_UPDATE_TEST_TOPOLOGY_OUTPUT" != 1 ]
 	then
-	    @DIFF@ -b @HWLOC_DIFF_U@ "$expected_output" "$output"
+	    @DIFF@ @HWLOC_DIFF_U@ @HWLOC_DIFF_W@ "$expected_output" "$output"
 	    result=$?
 	else
 	    if ! @DIFF@ "$expected_output" "$output" >/dev/null
@@ -80,54 +121,17 @@ test_topology ()
     return $result
 }
 
-# test_eligible TOPOLOGY-DIR
-#
-# Return true if the topology under TOPOLOGY-DIR is eligible for
-# testing with the current flavor.
-test_eligible()
-{
-    local dir="$1"
-    local output="$2"
-
-    [ -d "$dir" -a -f "$output" ]
-}
-
-
-if [ ! -x "$lstopo" ]
-then
-    error "Could not find executable file \`$lstopo'."
-    exit 1
-fi
-
-topology="${actual_output%.output}"
-if [ "$topology" = "$actual_output" ] ;
-then
-    error "Input file \`$1' should end with .output"
-    exit 1
-fi
-actual_options="$topology".options
-actual_source="$topology".tar.bz2
-
-# if there's a .env file, source it
-if [ -f "$topology".env ] ; then
-    . "$topology".env
-fi
-
 result=1
 
-dir="`mktemp -d`"
-
-if ! ( bunzip2 -c "$actual_source" | ( cd "$dir" && tar xf - $tar_options ) )
+if ! ( bunzip2 -c "$dirname/$source" | ( cd "$dir" && tar xf - $tar_options ) )
 then
-    error "failed to extract x86 cpuid \`$topology'"
+    error "failed to extract cpuid \`$source'"
 else
-    actual_dir="`echo "$dir"/*`"
+    actual_dir="`echo "$dir"/*/`"
 
-    if test_eligible "$actual_dir" "$actual_output"
+    if [ -d "$actual_dir" ]
     then
-	test_count="`expr $test_count + 1`"
-
-	test_topology "`basename $topology`" "$actual_dir" "$actual_output" "$actual_options"
+	test_topology "$actual_dir"
 	result=$?
     else
 	# Skip this test.
