Fix make dist during make distcheck
It wants to generate doxygen docs, but it doesn't by default
since it builds from a tarball. Force --enable-doxygen to fix that.

By the way, no need to double-check that doc/readme were generated
before building the tarball. config/distscript.csh is called on dist
and it does things as expected.

Also add a better error message when make dist fails because
PDFs do not exist yet, and doxygen isn't available.

Ideally, we'd just remove distscript.csh to make things much simpler
but I don't want to break more things today.

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -201,6 +201,13 @@ $(DOX_LETTERPDF): $(DOX_TAG)
 	   fi; \
 	done; \
 	mv letter-refman.pdf $(DOCDIR)/$(DOX_LETTERPDF)
+
+else
+$(DOX_A4PDF) $(DOX_LETTERPDF): no-build-pdfs
+no-build-pdfs:
+	@echo "ERROR: You do not have the 'doxygen' executable (or any related dependency) to build the PDF docs."
+	@echo "ERROR: Cannot continue."
+	@exit 1
 endif
 
 #
