tests/hwloc/xml: support XML input but non-XML output
tests are now listed by output.
non-XML outputs are specified by foo.output instead of foo.xml

diff --git a/tests/hwloc/xml/test-topology.sh.in b/tests/hwloc/xml/test-topology.sh.in
--- a/tests/hwloc/xml/test-topology.sh.in
+++ b/tests/hwloc/xml/test-topology.sh.in
@@ -3,7 +3,7 @@
 
 #
 # Copyright © 2009 CNRS
-# Copyright © 2009-2013 Inria.  All rights reserved.
+# Copyright © 2009-2015 Inria.  All rights reserved.
 # Copyright © 2009-2012 Université Bordeaux
 # Copyright © 2010-2014 Cisco Systems, Inc.  All rights reserved.
 # See COPYING in top-level directory.
@@ -51,15 +51,23 @@ fi
   tmp=$TMPDIR/foo$$-$RANDOM
   (umask 077 && mkdir "$tmp")
 } || exit $?
-file="$tmp/lstopo_xml.output.xml"
+file="$tmp/lstopo_xml.output"
 
 set -e
 
+output="$1"
 dirname=`dirname $1`
+filename=`basename $1`
 basename=`basename $1 .xml`
+basename=`basename $basename .output`
 
 source="${dirname}/${basename}.xml"
 source_file="${dirname}/${basename}.source"
+
+if test \! -f "$source" && test \! -f "$source_file"; then
+  echo "Missing both ${basename}.xml and ${basename}.source"
+  exit 1
+fi
 test -f "$source_file" && source="${dirname}/"`cat $source_file`
 
 options_file="${dirname}/${basename}.options"
@@ -74,34 +82,65 @@ do_run()
 
   if [ "$HWLOC_UPDATE_TEST_TOPOLOGY_OUTPUT" != 1 ]
   then
-    diff @HWLOC_DIFF_U@ @HWLOC_DIFF_W@ "${dirname}/${basename}.xml" "$file"
+    diff @HWLOC_DIFF_U@ @HWLOC_DIFF_W@ "$output" "$file"
   else
-    if ! diff "${dirname}/${basename}.xml" "$file" >/dev/null
+    if ! diff "$output" "$file" >/dev/null
     then
-	cp -f "$file" "${dirname}/${basename}.xml"
-	echo "Updated ${basename}.xml"
+	cp -f "$file" "$output"
+	echo "Updated $filename"
     fi
   fi
 
   if [ -n "@XMLLINT@" ]
   then
     cp -f "$HWLOC_top_srcdir"/hwloc/hwloc.dtd "$tmp/"
-    ( cd $tmp ; @XMLLINT@ --valid lstopo_xml.output.xml ) > /dev/null
+    ( cd $tmp ; @XMLLINT@ --valid $file ) > /dev/null
   fi
 
   rm "$file"
 }
 
+do_run_with_output()
+{
+  echo $lstopo --if xml --input "$source" "$file" $opts
+  $lstopo --if xml --input "$source" "$file" $opts
+
+  if [ "$HWLOC_UPDATE_TEST_TOPOLOGY_OUTPUT" != 1 ]
+  then
+    diff @HWLOC_DIFF_U@ @HWLOC_DIFF_W@ "$output" "$file"
+  else
+    if ! diff "$output" "$file" >/dev/null
+    then
+        cp -f "$file" "$output"
+        echo "Updated ${basename}.xml"
+    fi
+  fi
+
+  rm $file
+}
+
 export HWLOC_NO_LIBXML_IMPORT
 export HWLOC_NO_LIBXML_EXPORT
 
-echo "Importing with default parser and reexporting with minimalistic implementation..."
-HWLOC_NO_LIBXML_IMPORT=0
-HWLOC_NO_LIBXML_EXPORT=1
-do_run "$dirname" "$basename"
-echo "Importing with minimalistic parser and reexporting with default implementation..."
-HWLOC_NO_LIBXML_IMPORT=1
-HWLOC_NO_LIBXML_EXPORT=0
-do_run "$dirname" "$basename"
+if test "$filename" = "${basename}.xml"; then
+  echo "Importing with default parser and reexporting with minimalistic implementation..."
+  HWLOC_NO_LIBXML_IMPORT=0
+  HWLOC_NO_LIBXML_EXPORT=1
+  do_run "$dirname" "$basename"
+  echo "Importing with minimalistic parser and reexporting with default implementation..."
+  HWLOC_NO_LIBXML_IMPORT=1
+  HWLOC_NO_LIBXML_EXPORT=0
+  do_run "$dirname" "$basename"
+else if test "$filename" = "${basename}.output"; then
+  echo "Importing with default parser"
+  HWLOC_NO_LIBXML_IMPORT=0
+  do_run_with_output "$dirname" "$basename"
+  echo "Importing with minimalistic parser"
+  HWLOC_NO_LIBXML_IMPORT=1
+  do_run_with_output "$dirname" "$basename"
+else
+  echo "Filename must end with either .xml or .output"
+  exit 1
+fi fi
 
 rm -rf "$tmp"
