tests/linux/allowed: rewrite the framework with .test files
Replace the old .synthetic + .fsroot + .options + .env optional files with
a single mandatory .test file that contains everything.

foo.test should contain:
- synthetic: synthetic topology description
- fsroot: tarball filename for applying local restrictions (must be in same directory as foo.test)
- target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
- options: lstopo options, if any
- env: environment variable lines to be sourced, if any

By the way, remove gp_index/id just like we do in other tests.

Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>

diff --git a/tests/hwloc/linux/allowed/test-topology.sh.in b/tests/hwloc/linux/allowed/test-topology.sh.in
--- a/tests/hwloc/linux/allowed/test-topology.sh.in
+++ b/tests/hwloc/linux/allowed/test-topology.sh.in
@@ -9,9 +9,6 @@
 # See COPYING in top-level directory.
 #
 
-# Check the conformance of `lstopo' for all the Linux sysfs
-# hierarchies available here.  Return true on success.
-
 HWLOC_top_srcdir="@HWLOC_top_srcdir@"
 HWLOC_top_builddir="@HWLOC_top_builddir@"
 lstopo="$HWLOC_top_builddir/utils/lstopo/lstopo-no-graphics"
@@ -31,8 +28,6 @@ export HWLOC_DONT_ADD_VERSION_INFO
 HWLOC_XML_EXPORT_SUPPORT=0
 export HWLOC_XML_EXPORT_SUPPORT
 
-actual_output="$1"
-
 # make sure we use default numeric formats (only XML outputs are dis-localized when supported)
 LANG=C
 LC_ALL=C
@@ -43,27 +38,73 @@ error()
     echo $@ 2>&1
 }
 
+if [ ! -x "$lstopo" ]
+then
+    error "Could not find executable file \`$lstopo'."
+    exit 1
+fi
+
+testname="$1"
+dirname=`dirname $1`
+basename=`basename $1 .test`
+
+if test \! -f "$testname"; then
+  echo "Cannot find test file $testname"
+  exit 1
+fi
+
+dir="`mktemp -d`"
+
+####################################
+# foo.test should contain:
+# - synthetic: synthetic topology description
+# - fsroot: tarball filename for applying local restrictions (must be in same directory as foo.test)
+# - target: expected output filename (must be in same directory as foo.test, ends with either .console or .xml)
+# - options: lstopo options, if any
+# - env: environment variable lines to be sourced, if any
+
+synthetic=`sed -n 's/^synthetic: *//p' "$testname"`
+fsroot=`sed -n 's/^fsroot: *//p' "$testname"`
+target=`sed -n 's/^target: *//p' "$testname"`
+opts=`sed -n 's/^options: *//p' "$testname"`
+sed -n 's/^env: *//p' "$testname" > "$dir/env"
+
+if test \! -f "$dirname/$fsroot"; then
+  echo "Cannot find fsroot file $fsroot from test $testname"
+  exit 1
+fi
+if test \! -f "$dirname/$target"; then
+  echo "Cannot find target file $target from test $testname"
+  exit 1
+fi
+
+[ -z "$opts" ] && opts="-v -"
+if test "$target" = `basename $target .xml`".xml"; then
+  is_xml_target=1
+  opts="--of xml $opts"
+else
+  is_xml_target=0
+  opts="--of console $opts"
+fi
+
+. "$dir/env"
+
 # test_topology NAME TOPOLOGY-DIR
 #
 # Test the topology under TOPOLOGY-DIR.  Return true on success.
 test_topology ()
 {
-    local input="$1"
-    local dir="$2"
-    local expected_output="$3"
-    local options="$4"
+    local fsroot="$1"
+    local expected_output="$dirname/$target"
 
     local output="`mktemp`"
 
     export HWLOC_DEBUG_CHECK=1
+    export HWLOC_FSROOT="$fsroot"
 
-    opts="-v -"
-    [ -r "$options" ] && opts=`cat $options`
-
-    input=$(cat $input)
-    inputformat=synthetic
-
-    if ! HWLOC_FSROOT="$dir" "$lstopo" --if $inputformat -i "$input" $opts \
+    if ! "$lstopo" --if synthetic -i "$synthetic" $opts \
+        | sed   -e 's/ id="obj[0-9]*"//' \
+        | sed   -e 's/ gp_index="[0-9]*"//' \
 	> "$output"
     then
 	result=1
@@ -87,63 +128,17 @@ test_topology ()
     return $result
 }
 
-# test_eligible TOPOLOGY-DIR
-#
-# Return true if the topology under TOPOLOGY-DIR is eligible for
-# testing with the current flavor.
-test_eligible()
-{
-    local dir="$1"
-    local output="$2"
-
-    [ -d "$dir" -a -f "$output" ]
-}
-
-
-if [ ! -x "$lstopo" ]
-then
-    error "Could not find executable file \`$lstopo'."
-    exit 1
-fi
-
-topology="${actual_output%.output}"
-if [ "$topology" = "$actual_output" ] ;
-then
-    error "Input file \`$1' should end with .output"
-    exit 1
-fi
-
-actual_options="$topology".options
-
-actual_input="$topology".synthetic
-
-# if there's a .source file, use the tarball name it contains instead of $topology
-if [ -f "$topology".source ] ; then
-    actual_fsroot=`dirname $topology`/`cat "$topology".fsroot.source`
-else
-    actual_fsroot="$topology".fsroot.tar.bz2
-fi
-
-# if there's a .env file, source it
-if [ -f "$topology".env ] ; then
-    . "$topology".env
-fi
-
 result=1
 
-dir="`mktemp -d`"
-
-if ! ( bunzip2 -c "$actual_fsroot" | ( cd "$dir" && tar xf - $tar_options ) )
+if ! ( bunzip2 -c "$dirname/$fsroot" | ( cd "$dir" && tar xf - $tar_options ) )
 then
-    error "failed to extract topology \`$topology'"
+    error "failed to extract topology \`$fsroot'"
 else
-    actual_dir="`echo "$dir"/*`"
+    actual_dir="`echo "$dir"/*/`"
 
-    if test_eligible "$actual_dir" "$actual_output"
+    if [ -d "$actual_dir" ]
     then
-	test_count="`expr $test_count + 1`"
-
-	test_topology "$actual_input" "$actual_dir" "$actual_output" "$actual_options"
+	test_topology "$actual_dir"
 	result=$?
     else
 	# Skip this test.
