Fixes #3.
Have fixed versions of the man pages for the executables in svn under
the .1in filename pattern.  These files are processed during "make
all" to make the corresponding .1 files.  The changes that are added
in are the project name, date, and release version.  This gives
nice/proper headers and footers on the man pages that are specific to
the version that they came from.

This also fixes the issue of having the man pages depend on the
executables, which was causing problems for making nightly tarballs.

This commit was SVN r1001.

diff --git a/contrib/dist/make_dist_tarball b/contrib/dist/make_dist_tarball
--- a/contrib/dist/make_dist_tarball
+++ b/contrib/dist/make_dist_tarball
@@ -87,6 +87,32 @@ make_tarball() {
     fi
 
     #
+    # Explicitly create the doxygen docs
+    #
+    echo "*** Making doxygen docs..."
+    cd doc
+    rm -rf doxygen-doc
+    rm -f success
+    (make doc 2>&1 && touch success) | tee config.out
+    if test ! -f success; then 
+        echo "Making doxygen docs failed.  Aborting"
+        exit 1
+    fi
+
+    #
+    # Explicitly create the README file
+    #
+    echo "*** Making README..."
+    rm -rf ../README
+    rm -f success
+    (make readme 2>&1 && touch success) | tee config.out
+    if test ! -f success; then 
+        echo "Making README failed.  Aborting"
+        exit 1
+    fi
+    cd ..
+
+    #
     # make tarball
     #
     echo "*** Running make distcheck..."
@@ -143,9 +169,11 @@ fi
 echo "*** Removing svn version numbers..."
 svn_r="r`svnversion .`"
 version_files="`find . -name VERSION`"
+release_date=`date '+%b %d, %Y'`
 for file in $version_files; do
     echo " - $file"
     sed -e 's/^want_svn=.*/want_svn=0/' \
+        -e "s/^date=.*/date=\"$release_date\"/" \
         -e 's/^svn_r=.*/'svn_r=$svn_r/ $file > $file.new
     cp -f $file.new $file
     rm $file.new
