doc+contrib: switch the website doc to doxygen layout
The OMPI layout isn't easily compatible with the "treeview" doxygen
option, which is convenient for navigation (left sidebar).

So generate www.open-mpi.org docs without OMPI header/footer/CSS/PHP
and enable treeview.

Update contrib/dist/publish_doc accordingly.

Closes #160

Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
(cherry picked from commit 25db54ae4029d843c94df62dac608f839e56d2e4
                and commit 59f7156758591743d4612db205d9c75ebdacddf8)

diff --git a/contrib/dist/publish_doc b/contrib/dist/publish_doc
--- a/contrib/dist/publish_doc
+++ b/contrib/dist/publish_doc
@@ -66,13 +66,13 @@ echo "Installing hwloc-v${VERSION}-letter.pdf ..."
 cp -f doc/doxygen-doc/hwloc-letter.pdf "$dst/hwloc-v${VERSION}-letter.pdf"
 
 echo "Installing v${VERSION}/ HTML directory ..."
-rsync -avz doc/www.open-mpi.org*inc doc/www.open-mpi.org/html/ "$dst/v${VERSION}/"
+rsync -avz doc/www.open-mpi.org/html/ "$dst/v${VERSION}/"
 
 echo
 cd "$dst/v${VERSION}/"
 echo "Looking for URLs to be updated in links in main pages:"
 echo "- Link to examples:"
-grep -H ' id="cli_examples">' *.php || echo "Not found!"
+grep -H ' id="cli_examples">' *.html || echo "Not found!"
 echo "- Link to API upgrade in NEWS and tutorials:"
-grep -H ' class="title">Upgrading to the hwloc .* API<' *.php || echo "Not found!"
+grep -H ' class="title">Upgrading to the hwloc .* API<' *.html || echo "Not found!"
 cd ../..
